curl -X GET https://rest-api-murex-xi.vercel.app/mahasiswa -H "Authorization: Bearer 12345ABCDEF"

curl -X POST https://rest-api-murex-xi.vercel.app/mahasiswa -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{ "nama": "Hermione", "jurusan": "Hubungan Internasional"}'

curl -X PUT https://rest-api-murex-xi.vercel.app/mahasiswa/4 -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{"nama": "Luna Lov", "jurusan": "Farmasi"}'

curl -X DELETE https://rest-api-murex-xi.vercel.app/mahasiswa/2 -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json"
===========================
curl -X GET http://localhost:3000/

curl -X GET http://localhost:3000/mahasiswa -H "Authorization: Bearer 12345ABCDEF"

curl -X POST http://localhost:3000/mahasiswa -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{ "nama": "Harry", "jurusan": "Manajemen"}'

curl -X PUT http://localhost:3000/mahasiswa/2 -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{"nama": "Harry Potter", "jurusan": "Manajemen"}'

curl -X DELETE http://localhost:3000/mahasiswa/2 -H "Authorization: Bearer 12345ABCDEF"
===========================
curl -X GET https://rest-md11v0s2u-erenorrens-projects.vercel.app

curl -X GET https://rest-md11v0s2u-erenorrens-projects.vercel.app/mahasiswa -H "Authorization: Bearer 12345ABCDEF"

curl -X POST https://rest-md11v0s2u-erenorrens-projects.vercel.app/mahasiswa -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{ "nama": "Hermione", "jurusan": "Hubungan Internasional"}'

curl -X PUT https://rest-md11v0s2u-erenorrens-projects.vercel.app/mahasiswa/4 -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json" -d '{"nama": "Luna Lov", "jurusan": "Farmasi"}'

curl -X DELETE hhttps://rest-md11v0s2u-erenorrens-projects.vercel.app/2 -H "Authorization: Bearer 12345ABCDEF" -H "Content-Type: application/json"